server:
  port: 8081
spring:
  application:
    name: hmdp
  rabbitmq:
    host: 192.168.126.129
    port: 5672
    virtual-host: /zwf
    username: zwf
    password: zwf
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto #消费者确认机制
  #    publisher-confirm-type: correlated #MQ异步回调方式返回回执消息
#    connection-timeout: 200ms #设置mq的连接超时时间
#    template:
#      retry:
#        enabled: true #开启超时重试机制
#        initial-interval: 1000ms #失败后的初始等待时间
#        multiplier: 1 #失败后下次等待时长倍速
#        max-attempts: 2 #最大重试次数
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wfdp?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql17378054307
  redis:
    host: localhost  #192.168.126.129
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
